#!/usr/bin/env bash

# shellcheck source=/dev/null
source "${DOTFILES_ROOT}/lib/bash-utilities.sh"

if [[ -f /etc/os-release ]]; then
  source /etc/os-release
else
  log::fatal "Cannot detect OS: /etc/os-release missing."
fi

if [[ $ID != "debian" ]]; then
  log::warn "This script is for Pure Debian only. Detected: $ID"
  log::warn "Skipping mirror configuration to prevent system breakage."
  exit 0
fi

if [[ -z ${VERSION_CODENAME-} ]]; then
  log::fatal "Could not detect Debian codename (VERSION_CODENAME)."
fi

log::info "Configuring Debian Sources ($VERSION_CODENAME)"

TARGET_FILE="/etc/apt/sources.list"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="${TARGET_FILE}.backup_${TIMESTAMP}"

if [[ -f $TARGET_FILE ]]; then
  log::info "Backing up current sources to: $BACKUP_FILE"
  $SUDO_CMD cp "$TARGET_FILE" "$BACKUP_FILE"
fi

cat << EOF | $SUDO_CMD tee "$TARGET_FILE" > /dev/null
# ==============================================================================
# DEBIAN SOURCES LIST
# Generated by Dotfiles Bootstrap on $(date)
# Region: Global (deb.debian.org)
# ==============================================================================

# wiki   : https://wiki.debian.org/SourcesList

# 1. Main Repositories (Official, Contrib, Non-Free, Firmware)
deb http://deb.debian.org/debian ${VERSION_CODENAME} main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian ${VERSION_CODENAME} main contrib non-free non-free-firmware

# 2. Security Updates
deb http://deb.debian.org/debian-security/ ${VERSION_CODENAME}-security main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian-security/ ${VERSION_CODENAME}-security main contrib non-free non-free-firmware

# 3. Updates (Volatile)
deb http://deb.debian.org/debian ${VERSION_CODENAME}-updates main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian ${VERSION_CODENAME}-updates main contrib non-free non-free-firmware

# 4. Backports (Optional, often needed for newer kernels/drivers)
deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian ${VERSION_CODENAME}-backports main contrib non-free non-free-firmware
EOF

# 5. Refresh
# ------------------------------------------------------------------------------
log::info "Updating package lists..."
$SUDO_CMD apt-get update

log::info "Upgrading package lists..."
$SUDO_CMD apt-get upgrade -y

log::info "Debian sources configured successfully."

# install a package using backports
# sudo apt install -t bookworm-backports <package-name>
