alacritty=alacritty
polybar=polybar

gst_base=gstreamer1
gst_plugins_good=gstreamer1-plugins-good
gst_plugins_bad=gstreamer1-plugins-bad-free
gst_plugins_ugly=gstreamer1-plugins-ugly
gst_libav=gstreamer1-plugin-libav
ffmpeg_extra_codecs=ffmpeg

lib_heif=libheif
lib_heif_examples=libheif-tools
heif_gdk_pixbuf=libheif-gdk-pixbuf
heif_thumbnailer=libheif-thumbnailer
lib_de265=libde265

lib_avif=libavif
lib_aom=libaom
lib_dav1d=libdav1d
lib_webp=libwebp
lib_jpeg_turbo=libjpeg-turbo-devel
lib_jxl=libjxl
lib_raw=LibRaw
lib_exiv2=exiv2-libs
lib_openjpeg=openjpeg2

lib_mp3lame=lame
lib_opus=opus
lib_vorbis=libvorbis
lib_aac=faac
lib_flac=flac

lib_x264=x264-libs
lib_x265=x265-libs
lib_vpx=libvpx
lib_svtav1=svt-av1
lib_dvd_nav=libdvdnav
lib_dvd_read=libdvdread

vainfo=libva-utils
mesa_va_drivers=mesa-va-drivers
lib_va=libva

font_ms_core=mscore-fonts-all
font_ms_ttf=mscore-fonts-all
