# Mimeapps and Desktop Entries
apps/mimeapps-list/mimeapps.list|.config/mimeapps.list|0755
apps/mimeapps-list/mimeapps.list|.local/share/applications/mimeapps.list|0755
apps/mimeapps-list/desktop-entries/secure-mpv.desktop|.local/share/applications/secure-mpv.desktop|0755
apps/mimeapps-list/desktop-entries/secure-zathura.desktop|.local/share/applications/secure-zathura.desktop|0755
apps/mimeapps-list/desktop-entries/secure-sxiv.desktop|.local/share/applications/secure-sxiv.desktop|0755

# Viewers (Zathura & Sxiv)
apps/zathura|.config/zathura|0755
apps/sxiv/exec/image-info.sh|.config/sxiv/exec/image-info|0755
apps/sxiv/exec/key-handler.sh|.config/sxiv/exec/key-handler|0755

# Shell & UI
apps/lxterminal/lxterminal.conf|.config/lxterminal/lxterminal.conf|0755
apps/sxhkd|.config/sxhkd|0755
apps/rofi|.config/rofi|0755

# VSCode
apps/vscode/keybindings.json|.config/Code/User/keybindings.json|0755
apps/vscode/settings.json|.config/Code/User/settings.json|0755

# OBS Studio
apps/obs-studio/profiles|.config/obs-studio/basic/profiles|0755
apps/obs-studio/scenes|.config/obs-studio/basic/scenes|0755
apps/obs-studio/global.ini|.config/obs-studio/global.ini|0755

# Openbox
apps/openbox/autostart|.config/openbox/autostart|0755
apps/openbox/environment|.config/openbox/environment|0755
apps/openbox/menu.xml|.config/openbox/menu.xml|0755
apps/openbox/rc.xml|.config/openbox/rc.xml|0755

# Xorg
apps/xorg/.Xresources|.Xresources|0755

# Firefox User Profile
apps/firefox/user.js|.mozilla/firefox/custom-profile/user.js|0644
apps/firefox/userChrome.css|.mozilla/firefox/custom-profile/chrome/userChrome.css|0644
