# GRUB Settings for Virtual Machines (High resolution console)
GRUB_TERMINAL_OUTPUT="gfxterm"
GRUB_GFXMODE="1920x1080x32,1024x768,auto"
GRUB_GFXPAYLOAD_LINUX_DEFAULT="quiet video=1280x1024"
GRUB_GFXPAYLOAD_LINUX="keep"
